# Generated by Django 4.2.9 on 2024-01-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='clue',
            name='password',
        ),
    ]
