# Generated by Django 4.2.9 on 2024-02-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj1', '0003_clue_city_clue_fans_clue_group_clue_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='note',
            new_name='status',
        ),
        migrations.AddField(
            model_name='clue',
            name='audits',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clue',
            name='settle',
            field=models.CharField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clue',
            name='city',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clue',
            name='province',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
