# Generated by Django 4.2.9 on 2024-02-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj1', '0004_rename_note_clue_status_clue_audits_clue_settle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='audits',
            field=models.CharField(default='未审核', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clue',
            name='settle',
            field=models.CharField(default='未结算', null=True),
        ),
        migrations.AlterField(
            model_name='clue',
            name='status',
            field=models.CharField(default=0, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
