# Generated by Django 4.2.9 on 2024-02-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj1', '0007_alter_clue_wechat_clue_unique_wechat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='club',
            field=models.CharField(max_length=32),
        ),
    ]
